### ISSUE TITLE
How to compile the template under texlive-2015

### ISSUE THREAD

**Issue by zhujianwei31415** [xiaoyao9933/UCASthesis#1]
Can you fix the bug in compiling the template under "texlive-2015"?
I got the error:

Undefined control sequence.
l.82   \ifCTEX@nofonts

**Comment by xiaoyao9933** [comment]
你是什么系统呢？告诉我您执行的命令，我复现一下。

**Comment by zhujianwei31415** [comment]
我是Mac OS X 10.11.2 + MacTeX2015，字体已经安装好了

PS，清华的那个模板出过类似问题，不过他改过之后就可以了，然后我在电脑上可以编译。查了一下他说是texlive-2015的问题。

**Comment by xiaoyao9933** [comment]
哦，我用的还是2014版本，新版本我确实还没做适配，你要是急着用的话，你可以上我这里拷一下mac tex 2014的版本。我得下载一个2015的版本试试，tex的发行版总是乱删改。

**Comment by zhujianwei31415** [comment]
忘记说了，我直接使用make 或者make all出的问题。

PS，非常感谢你的帮助！

**Comment by zhujianwei31415** [comment]
不急着用，我也把版本降下来了，然后进行编译的。

我就是想你能不能做好适配，以后不小心升级了或者在其他电脑上版本升级之后可以继续使用。

然而我还不会搞，只能求助了。这东西只能大神来搞，我就是用template的那种，看源码都晕了。

**Comment by xiaoyao9933** [comment]
刚刚屏蔽了nofonts设置了，采用了和清华模板一样的固定字体设置方案，还有一些小的修正。 你试下这个分支
https://github.com/xiaoyao9933/UCASthesis/tree/test-comp , 既然你降到了2014版本，先试下2014的，最后再试2015的。我现在改为2015的版本了，一会儿我降下来再试试。

**Comment by xiaoyao9933** [comment]
2014版本似乎也是对的了。

**Comment by zhujianwei31415** [comment]
经过测试MacTeX2014顺利通过测试，MacTeX2015也顺利通过测试。

大神就是大神，果然厉害！

谢谢！

**Comment by xiaoyao9933** [comment]
没事儿，客气啦，感谢你的发现~
