### ISSUE TITLE
行距的设置有误

### ISSUE THREAD

**Issue by zepinglee** [xiaoyao9933/UCASthesis#12]
```
\newcommand{\ucas@choosefont}[2]{%
   \setlength{\ucas@linespace}{#2*\real{#1}}%
   \fontsize{#2}{\ucas@linespace}\selectfont}
\def\ucas@define@fontsize#1#2{%
  \expandafter\newcommand\csname #1\endcsname[1][\baselinestretch]{%
    \ucas@choosefont{##1}{#2}}}
\ucas@define@fontsize{xiaosi}{12bp}
```
这样设置的行距是错的，比如 \baselinestretch 是 1.2 时，实际的行距是字号的 1.2^2 = 1.44 倍。

另外这个项目跟 https://github.com/mohuangrui/ucasthesis 有什么联系和区别？

**Comment by xiaoyao9933** [comment]
额，好久没维护了，国科大给的论文模板行距好像也不太对，我只能说这个行距肉眼感觉还可以，我之后有空再调吧。
没关系。我比他做的更早些，我是5年前基于清华大学的论文模板改的，mohuangrui是他自己又写的一个，区别细节还挺多的，模板这种东西每个人做出来都不一样。

**Comment by zepinglee** [comment]
看来 thuthesis 早年的这个 bug 影响了一大批模板
