### ISSUE TITLE
The compilation is extremely slow

### ISSUE THREAD

**Issue by jindongwang** [xiaoyao9933/UCASthesis#13]
First of all, I want to thank you for maintaining such a useful template!
My PC is Windows 10 OS, with TexLive 2017 as the tex core and TexStudio as the IDE. 
However, I found that the compilation is extremely slow here. I use xelatex. Each compilation and build will take more than 10 seconds. Is that correct?

**Comment by xiaoyao9933** [comment]
Since every full compilation will execute at 3 times xelatex, you can just execute one time for a draft version.

**Comment by jindongwang** [comment]
@xiaoyao9933 Thanks for your timely answer!
I cannot generate the references. My configuration is as follows, could you please tell me what's wrong?

![qq 20181217155126](https://user-images.githubusercontent.com/6158206/50073511-c8eb2a80-0213-11e9-9f19-b4944fc6e946.png)

**Comment by xiaoyao9933** [comment]
不同的IDE工具确实有不同的设置，我也不知道你这个怎么回事，你得看看自己的错误信息。

**Comment by jindongwang** [comment]
好的，我再研究研究，谢谢啦！

**Comment by jindongwang** [comment]
@xiaoyao9933 重启电脑就好了。。。
