### ISSUE TITLE
宋体加粗，为啥是变成了黑体。。。

### ISSUE THREAD

**Issue by jindongwang** [xiaoyao9933/UCASthesis#14]
比如封面作者信息啥的，都是宋体加粗，但为啥都变成了黑体呢？

**Comment by xiaoyao9933** [comment]
我在FAQ里解释过。LaTex没有粗体，是利用位移重叠弄出的假粗体，很难看，所以这些年一直用的都是黑体替代宋体粗体，没啥事儿的。

**Comment by jindongwang** [comment]
原来是这样。。。感谢回答！那封面啥的都是黑体了，是不是和国科大那个说明不太符合呀，不知道会不会因为这个麻烦

**Comment by xiaoyao9933** [comment]
不要太在意这个问题，没人查你格式的，模板做不到那么精确的。另一个UCASThesis模板，也是这么干的。好多年都顺利走过来了。

参见：
https://github.com/mohuangrui/ucasthesis/issues/23

**Comment by jindongwang** [comment]
他这个我也用过，用xelatex编译就能成为加粗的宋体，你这个不行，太诡异了。。
他这个有另一个问题：多个subfigure的时候，最后一个的字是加粗或模糊的，解决不了。。。

**Comment by xiaoyao9933** [comment]
他那个有一段时间用过fake bold，也用过黑体，还有用过fandol字体替代黑色的。我没咋琢磨过。

**Comment by jindongwang** [comment]
嗯嗯，感谢！还有个问题：我怎么改页面左右边距，现在貌似有点太宽了，和以前实验室毕业的师姐的比起来一行少了4-5个字

**Comment by xiaoyao9933** [comment]
你把attachment目录下的学术规范打开看看呢？应该没有太大差别。去年论文模板改版成国科大的了，发生了很多变化。你师姐用的可能用的是计算所老模板，不是国科大新模板。

**Comment by jindongwang** [comment]
谢谢！国科大这个规范是这样的：

![qq 20190307202328](https://user-images.githubusercontent.com/6158206/53956553-e6df7180-4116-11e9-90c3-f84f780d3ac2.png)

现在模版里我找到有关页边距的是这样：

![qq 20190307202229](https://user-images.githubusercontent.com/6158206/53956564-ec3cbc00-4116-11e9-84ea-a2dccd3f28f8.png)

不知道应该怎么该。。。

**Comment by xiaoyao9933** [comment]
说来惭愧，我的latex模板功底一直是照猫画虎，这个数字是我一点点对照屏幕试出来的。latex边距的计算好像没这么简单就能调。

**Comment by jindongwang** [comment]
好像是挺复杂的。。。我先不改了吧。谢谢你及时的回复！
