### ISSUE TITLE
file 'zhnumber.sty' not found

### ISSUE THREAD

**Issue by alanse7en** [xiaoyao9933/UCASthesis#2]
I'm using ctex. pdflatex or xelatex gives the error:
Latex error: file 'zhnumber.sty' not found

Do U know how to fix this? Thanks.

**Comment by xiaoyao9933** [comment]
Use miktex or texlive's package manager to download the zhnumber package. If you are using miktex, TeXworks application can download the dependencies automatically.

**Comment by xiaoyao9933** [comment]
It says CTeX is based on MikTex, and you can run its utility called TeXworks to compile the main.tex file.
