### ISSUE TITLE
Bst格式文件对webpage类型文献支持不好

### ISSUE THREAD

**Issue by dotweiba** [xiaoyao9933/UCASthesis#3]
Bst格式文件对webpage类型文献支持不好，会在引用条目中加入出版社和出版地点信息。

**Comment by xiaoyao9933** [comment]
@dotweiba 请告知我你的bibtex里文献的格式是怎样的？

**Comment by dotweiba** [comment]
@xiaoyao9933 如这样的:

> @webpage{Anonymous:y7bnmDo4,
> title = {{Common Vulnerabilities and Exposures}},
> url = {https://cve.mitre.org},
> citedate = {2017-2-17},
> author = {CVE},
> year = {2017}
> }
> 

会生成

> [n] CVE. Common Vulnerabilities and Exposures[M].[S.l.]: [s.n.] , 2017[2017-2-17]. https://cve.mitre. org.  

这样的引用。其中[S.l.]和[s.n.]位置是出版社和出版地点信息，可是GBT标准是没有如这样的格式。

**Comment by xiaoyao9933** [comment]
@dotweiba  是的，这个BST是有点问题，太古老了。

你用这个里面的bst来替换吧，https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style
看起来比较全，你测试下，如果没问题的话，我过几天更新到代码里去。多谢。

**Comment by dotweiba** [comment]
@xiaoyao9933 这个BST没有此问题。另外我细看了一下GBT714-2005的标准，电子文献类型的引用格式可以有出版社和出版地点，但似乎不是强制的。
