### ISSUE TITLE
编译以后的参考文献，作者全都是大写？

### ISSUE THREAD

**Issue by lzhaozi** [xiaoyao9933/UCASthesis#5]
是今年的模板改成这样了么？还是说是模板设置或者参数有问题？

**Comment by lzhaozi** [comment]
![Uploading 未命名.jpg…]()

![Uploading 未命名.jpg…]()

**Comment by xiaoyao9933** [comment]
这个是gbt7714-2005的规范要求，理论上要遵守的。
