### ISSUE TITLE
声明页内容已更新，需变更

### ISSUE THREAD

**Issue by kattyjoy** [xiaoyao9933/UCASthesis#6]
经人提醒，对比了今年新发的word论文模板，发现声明页两个声明的内容和格式已经变更了，例如标题新加了一行“中国科学院大学”，内容中去掉了计算所等字样。

相应的cfg文件中的内容应变更，由于本人也是刚接触latex，尝试改了一下但格式不对，所以抛砖引玉下

**Comment by kattyjoy** [comment]
目前我的解决方法是用pdfpages包，在论文内容之前直接插入一页已经打印好的声明页pdf，打印之后手动替换

**Comment by xiaoyao9933** [comment]
不好意思，才看到，可否让我看一下最新的模板长什么样子？

**Comment by kattyjoy** [comment]
不好意思，我也才看到，论文模板我这里还有，我怎么发给你呢？

**Comment by xiaoyao9933** [comment]
您好，请发送到me@chao.lu吧。

**Comment by xiaoyao9933** [comment]
模板已统一更新为2018国科大版本~
