### ISSUE TITLE
副导师出不来

### ISSUE THREAD

**Issue by zhaohe1670** [xiaoyao9933/UCASthesis#7]
\csupervisor{冒 \hspace{0.5em}研究员 \hspace{0.5em} 中国科学院}
\cassosupervisor{魏  \hspace{0.5em}研究员 \hspace{0.5em} 中国科学院}

这两句命令出现的结果只有正导师，副导师没结果，为甚么啊？

**Comment by xiaoyao9933** [comment]
副导师是清华大学原来模板才有的选项，这个是因为我当时做模板时发现，计算所这边很少写副导师，如果有副导师，直接在导师那栏换行写第二个人即可。官方word模板也没有没有副导师的选项。

**Comment by zhaohe1670** [comment]
\csupervisor{冒立军 \hspace{0.5em}研究员 \hspace{0.5em} 中国科学院近代物理研究所\\魏宝文  \hspace{0.5em}研究员 \hspace{0.5em} 中国科学院近代物理研究所}

我尝试这样写，但是编译时出现错误：
! Misplaced \cr.
\reserved@c ->\ifnum 0=`{}\fi \cr 
                                  
l.32 \makecover

**Comment by xiaoyao9933** [comment]
\csupervisor{冒立军 \hspace{0.5em}研究员 \hspace{0.5em} 中国科学院近代物理研究所}
\csupervisorplace{魏宝文 \hspace{0.5em}研究员 \hspace{0.5em} 中国科学院近代物理研究所}

如果你觉得这样可以的话，弄成两行能凑合一下，我就不改代码了，实在不知道这个副导师的正确格式如何书写。

**Comment by zhaohe1670** [comment]
可以可以，非常感谢
