### ISSUE TITLE
Package biblatex Error: Option 'date=year' invalid.

### ISSUE THREAD

**Issue by zwyzwy** [xiaoyao9933/UCASthesis#8]
一直出现这个问题怎么办？
Package biblatex Error: Option 'date=year' invalid. ...gle{iftlfive}{\switchversion{3.0}{opt}}{}

文献引用一直编译不出来，好烦躁，调了好久还是不行，求帮助啊大神

**Comment by xiaoyao9933** [comment]
git clone后的模板在不做任何改动的情况是否能够编译？

**Comment by zwyzwy** [comment]
编译不了

**Comment by xiaoyao9933** [comment]
什么系统？ texlive什么版本还是miktex？ 用的是否是XeLatex+Biber方式编译

**Comment by zwyzwy** [comment]
miktex，用的是XeLatex+Biber方式编译没错

**Comment by xiaoyao9933** [comment]
跟你说话好费劲啊。。。什么系统？ miktex什么版本？ 没错又是怎么回事了？

**Comment by zwyzwy** [comment]
Windows系统，miktex2.9，用的编译方式是XeLatex+Biber，

**Comment by xiaoyao9933** [comment]
人在计算所么？用的什么IDE？我无法复现你的错误。

**Comment by zwyzwy** [comment]
我在软件所，用的IDE是texstudio，方便的话可否麻烦帮我远程调一下？

**Comment by xiaoyao9933** [comment]
留个qq， 我装个texstudio试一下。

**Comment by xiaoyao9933** [comment]
留个qq， 我装个texstudio试一下。

**Comment by zwyzwy** [comment]
762134902
多谢大神

**Comment by xiaoyao9933** [comment]
这个是因为你的biblatex包的版本太老旧了，gst 7714-2015参考文献模板要求最低的版本是3.0，所以你需要通过texlive或者miktex的包管理更新一下这个包。
